const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];let currentId=null,currentFindings=[];
function show(name){$$('.view').forEach(x=>x.classList.add('hidden'));$(`#${name}-view`).classList.remove('hidden');$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===name));window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav').forEach(b=>b.onclick=()=>b.dataset.view==='history'?loadHistory():show('new'));
['back-new','back-new-2','back-new-3'].forEach(id=>{const e=$(`#${id}`);if(e)e.onclick=()=>show('new')});
$('#all-checks').onclick=()=>{$$('.check input').forEach(x=>x.checked=true)};
$('#spec-file').onchange=async e=>{const f=e.target.files[0];if(f){$('#spec-url').value='';$('#spec-url').placeholder=`Uploaded: ${f.name}`}};
$('#scan-form').onsubmit=async e=>{e.preventDefault();$('#form-error').textContent='';let tokens;try{tokens=JSON.parse($('#tokens').value||'{}')}catch{ $('#form-error').textContent='Auth tokens must be valid JSON.';return}let body={spec_url:$('#spec-url').value||null,target_base_url:$('#target-url').value,auth_tokens:tokens,checks:$$('.check input:checked').map(x=>x.value),authorization_confirmed:$('#authorized').checked};const file=$('#spec-file').files[0];if(file){body.spec_content=await file.text();body.spec_url=null}try{const r=await fetch('/api/scans',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.detail||'Could not start scan');currentId=data.id;show('progress');poll()}catch(err){$('#form-error').textContent=err.message}};
async function poll(){if(!currentId)return;const r=await fetch(`/api/scans/${currentId}`),s=await r.json();const pct=s.total?Math.round((s.progress/s.total)*100):0;$('#progress-number').textContent=pct+'%';$('#progress-bar').style.width=pct+'%';$('#scan-status').textContent=s.status.toUpperCase();$('#progress-title').textContent=s.status==='completed'?'Scan complete':s.status==='failed'?'Scan failed':'Scanning target contract';$('#progress-detail').textContent=s.total?`${s.progress} of ${s.total} endpoints processed`:(s.error||'Loading OpenAPI contract…');if(s.status==='completed'){await loadFindings();show('findings')}else if(s.status==='failed'){return}else setTimeout(poll,650)}
async function loadFindings(){const r=await fetch(`/api/scans/${currentId}/findings`);currentFindings=await r.json();renderFindings();}
function renderFindings(){const counts={Critical:0,High:0,Medium:0,Low:0};currentFindings.forEach(f=>counts[f.severity]=(counts[f.severity]||0)+1);$('#summary').innerHTML=Object.entries(counts).map(([k,v])=>`<div class="metric"><b>${v}</b><span>${k}</span></div>`).join('');const filter=$('#severity-filter').value;const arr=filter==='all'?currentFindings:currentFindings.filter(f=>f.severity===filter);$('#findings-table').innerHTML=arr.length?arr.map((f,i)=>`<div class="finding-row" data-i="${currentFindings.indexOf(f)}"><div><span class="badge ${f.severity.toLowerCase()}">${f.severity}</span></div><div><div class="row-title">${esc(f.title)}</div><div class="row-meta">${f.method} ${esc(f.endpoint)} · ${esc(f.vulnerability_class)}</div></div><div class="row-meta">${esc(f.vulnerability_class)}</div><div class="row-meta">View →</div></div>`).join(''):'<div class="empty">No findings match this filter.</div>';$$('.finding-row').forEach(x=>x.onclick=()=>detail(currentFindings[+x.dataset.i]));}
$('#severity-filter').onchange=renderFindings;
function detail(f){const d=$('#detail');d.classList.remove('hidden');d.innerHTML=`<div class="detail-head"><span class="badge ${f.severity.toLowerCase()}">${f.severity} · ${esc(f.vulnerability_class)}</span><h3>${esc(f.title)}</h3></div><section><label>What happened</label><p>${esc(f.description)}</p></section><section><label>Evidence</label><p>${esc(f.evidence)}</p></section><section><label>Proof of concept <button class="copy" data-copy="${encodeURIComponent(f.poc_curl)}">Copy</button></label><div class="code">${esc(f.poc_curl)}</div></section><section><label>Suggested fix</label><p>${esc(f.remediation)}</p></section>`;d.querySelector('.copy').onclick=async e=>{await navigator.clipboard.writeText(decodeURIComponent(e.target.dataset.copy));e.target.textContent='Copied'};d.scrollIntoView({behavior:'smooth',block:'start'})}
async function loadHistory(){show('history');const r=await fetch('/api/scans'),rows=await r.json();$('#history-table').innerHTML=rows.length?rows.map(s=>`<div class="history-row"><div><b>${s.id.slice(0,8)}</b><div class="row-meta">${new Date(s.created_at).toLocaleString()} · ${esc(s.target_base_url)}</div></div><span class="status">${s.status.toUpperCase()}</span><span class="row-meta">${s.progress}/${s.total} endpoints</span><button class="secondary open-scan" data-id="${s.id}">Open</button></div>`).join(''):'<div class="empty">No scans yet.</div>';$$('.open-scan').forEach(b=>b.onclick=async()=>{currentId=b.dataset.id;await loadFindings();show('findings')})}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
